# -*- coding: utf-8 -*-
"""IITG- summer analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X4IG_Qw-sLbAWgN5a_VJNgLFmrk96Y6I
"""

!pip install bokeh panel --quiet

import pandas as pd
import numpy as np
from bokeh.plotting import figure, show, output_notebook
output_notebook()


file_id = '1V6NlwFalOXyBdl-UAXA-e51cDyGbkosY'
url = f'https://drive.google.com/uc?id={file_id}&export=download'
df = pd.read_csv(url)

df['LastUpdatedDateTime'] = pd.to_datetime(
    df['LastUpdatedDate'].astype(str) + ' ' + df['LastUpdatedTime'].astype(str),
    format='%d-%m-%Y %H:%M:%S'
)

#Feature engineering
df['OccupancyRate'] = df['Occupancy'] / df['Capacity']

traffic_map = {'low': 1, 'medium': 2, 'high': 3}
df['TrafficConditionNumeric'] = df['TrafficConditionNearby'].map(traffic_map)

vehicle_map = {'car': 1, 'bike': 0.5, 'truck': 1.5}
df['VehicleTypeNumeric'] = df['VehicleType'].map(vehicle_map)

def dynamic_price(row, base_price=10):
    price = base_price
    price += 8 * row['OccupancyRate']
    price += 2 * row['QueueLength'] / 10
    price += 3 * row['TrafficConditionNumeric'] / 3
    price += 2 * row['IsSpecialDay']
    price += 1.5 * row['VehicleTypeNumeric']
    return np.clip(price, 5, 25)

df['DynamicPrice'] = df.apply(dynamic_price, axis=1)

lot_id = df['SystemCodeNumber'].unique()[0]
lot_data = df[df['SystemCodeNumber'] == lot_id].copy()

lot_data['SmoothedPrice'] = lot_data['DynamicPrice'].rolling(window=5, min_periods=1).mean()

p = figure(title=f"Dynamic Price Trend for Lot {lot_id}",
           x_axis_label='Time', y_axis_label='Price ($)', x_axis_type='datetime', width=800)

p.line(lot_data['LastUpdatedDateTime'], lot_data['DynamicPrice'], line_width=2, color='navy', legend_label='Dynamic Price')
p.line(lot_data['LastUpdatedDateTime'], lot_data['SmoothedPrice'], line_width=2, color='orange', legend_label='Smoothed Price')
p.legend.location = "top_left"
show(p)